import { v4 as uuidv4 } from "uuid";

export const data = [
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
  {
    id: uuidv4(),
    title: "Task 1",
    description: "Description 1",
    assignee: "John",
    priority: "Low",
    dueDate: "2024-10-20",
    status: "To Do",
  },
  {
    id: uuidv4(),
    title: "Task 2",
    description: "Description 2",
    assignee: "Jane",
    priority: "High",
    dueDate: "2024-10-21",
    status: "In Progress",
  },
];